### ISSUE TITLE
wsfe: comprobante emitido en moneda extranjera

### ISSUE THREAD

**Issue by lukio** [tryton-ar/account_invoice_ar#170]
Si el comprobante emitido es en una moneda extranjera (diferente a peso argentino), y el webservice utilizado es wsfe entonces en el reporte de factura se debe agregar una leyenda que exprese en que moneda fue emitido el comprobante y el valor de la cotización.

Dos posibilidades:

1. Esta leyenda podría ser agregada al campo "comment" al contabilizar el comprobante, y de esa manera, no es necesario generar la leyenda en el momento del reporte.

2. Generar la leyenda en el momento del reporte.

Sea como fuera, se requiere guardar en un campo aparte el valor de la cotización. Actualmente lo tenemos solamente en el request del xml.

**Comment by pablo-pinko** [comment]
Buen día Lukio soy Pablo de Luma, pido mil disculpas si esta no es la forma apropiada de expresarme, estoy abierto a sugerencias sobre como manejarme en estos sitios. Mi consulta es la siguiente: al generar una FC en moneda extranjera AFIP me devuelve este error:
"1667: El tipo de cambio no podr ser inferior al 20% ni superior en un 100% del que suministra AFIP como orientativo de acuerdo a la cotizacin oficial. Ver Metodo FEXGetPARAM_Ctz."
La tasa de cambio que manejamos (self.currency_rate) es 0.015888 (o sea 1 / 63)
Cuando miro el código veo que la cotización es seteada en la linea 1460: ctz = self.currency_rate
por lo tanto AFIP recibe 0.015888 en lugar de 63 como cotización. Cuando probé 
ctz = 1 / self.currency_rate lo tomó sin problemas, pero no estoy seguro si esta es la forma de proceder. Desde ya muchas gracias. Saludos!

**Comment by lukio** [comment]
Cierro este ticket, porque lo más importante era poder guardar el valor de la cotización en un campo separado, y eso fue agregado con el commit: 994b623
