### ISSUE TITLE
Recuperar Factura

### ISSUE THREAD

**Issue by leito** [tryton-ar/account_invoice_ar#28]
Para cuando hay un error de comunicación con la AFIP y se genera una inconsistencia entre los datos que tiene la AFIP y lo que esta registrado en el sistema. Sería deseable poder recuperar los datos de una factura

**Comment by lukio** [comment]
Creamos el módulo recover_invoice_ar https://github.com/tryton-ar/recover_invoice_ar para poder recuperar y corregir una factura que por una situación ha quedado aprobada en la AFIP y no ha pasado a estado Confirmada en nuestro sistema Trtyton.
