### ISSUE TITLE
Conflicto con modulo sale_pos

### ISSUE THREAD

**Issue by lukio** [tryton-ar/account_invoice_ar#45]
Error informado por Cecilia Popper:

He instalado el módulo sale_pos que permite hacer ventas rapidas (sobre todo nos sirve para las ventas de nuestro local a la calle, ya que permite hacer las ventas en un solo clic)
El problema es que al querer generar la factura (en el mòdulo se genera haciendo clic en "Pay") me aparece este error: 

> Error "El campo «Tipo de factura» en «Factura» es requerido."

El módulo sale_pos tiene como dependencia trytond_sale, el cual a su vez tiene las siguientes dependencias:
* trytond_company (http://www.tryton.org/)
* trytond_party (http://www.tryton.org/)
* trytond_stock (http://www.tryton.org/)
* trytond_account (http://www.tryton.org/)
* trytond_product (http://www.tryton.org/)
* trytond_account_invoice (http://www.tryton.org/)
* trytond_currency (http://www.tryton.org/)
* trytond_account_product (http://www.tryton.org/)

**Comment by agumontagna** [comment]
Hola Lukio, respecto a lo que te comentamos, el problema es que el hecho de que quede la configuración de la factura marcada como "manual" no es para nada práctico dado que al procesar o vender algo, no se generan las facturas.
Habría manera de dejarlo seteado con la configuración tradicional "al procesar la orden"??  
Si esto funciona, se vuelven compatibles ambos módulos. 

*Este Cartel solicitando configuración Manual aparece aunque ya esté la conf en manual. 
![selection_013](https://cloud.githubusercontent.com/assets/10468877/8337503/ea77feda-1a81-11e5-9c92-62df8c87747e.png)

**Comment by lukio** [comment]
Hola Agustin, ese cambio se sacó (issue #53) en el commit: 7c4d33d4990
Justamente, ahora ya no es una limitante si viene de una compra o una venta, así que pueden configurar que genere la factura "al procesar la orden" en el modulo de Ventas. 

Se verifica si tenemos los datos necesarios pasar al estado Validated o Confirmado en vez de hacerlo al guardar la Factura.

**Comment by agumontagna** [comment]
Genial, sí, ya lo pude sacar adelante. 
Muchas Gracias Lukio!
