### ISSUE TITLE
Error al pasar a producción config de empresas

### ISSUE THREAD

**Issue by pablovannini** [tryton-ar/account_invoice_ar#46]
El commit #35 permite configurar desde empresa el certificado AFIP y se testea la conección, homologación funciona ok, pero al intentar pasar a modo producción:

Problemas de Certificado: "X509Error: 3028286320:error:0906D06C:PEM routines:PEM_read_bio:no start line:pem_lib.c:703:Expecting: CERTIFICATE

**Comment by ceciliasp** [comment]
Chicos, hay alguna novedad sobre este issue? Gracias!

**Comment by lukio** [comment]
Esto ya esta funcionando correctamente.

**Comment by ceciliasp** [comment]
Gracias!
