### ISSUE TITLE
Al procesar Compra

### ISSUE THREAD

**Issue by lukio** [tryton-ar/account_invoice_ar#53]
Me pide Tipo de comprobante en "Factura" es requerido, y no puede continuar.

![captura de pantalla de 2015-05-18 11 49 01](https://cloud.githubusercontent.com/assets/776682/7683229/f7f72dec-fd53-11e4-9db8-bfdd1945bc71.png)

**Comment by agumontagna** [comment]
Perfecto! Faltaría comentar la línea 150 que requiere tipo de comprobante.
