### ISSUE TITLE
Error al imprimir una factura confirmada

### ISSUE THREAD

**Issue by germanp** [tryton-ar/account_invoice_ar#55]
Me tira el siguiente error:

```python
Traceback (most recent call last):
  File "/trytond/protocols/jsonrpc.py", line 150, in _marshaled_dispatch
    response['result'] = dispatch_method(method, params)
  File "/trytond/protocols/jsonrpc.py", line 179, in _dispatch
    res = dispatch(*args)
  File "/trytond/protocols/dispatcher.py", line 161, in dispatch
    result = rpc.result(meth(*c_args, **c_kwargs))
  File "/trytond/modules/account_invoice/invoice.py", line 2450, in execute
    res = super(InvoiceReport, cls).execute(ids, data)
  File "/trytond/report/report.py", line 144, in execute
    type, data = cls.parse(action_report, records, data, {})
  File "/trytond/modules/account_invoice_ar/invoice.py", line 700, in parse
    localcontext['condicion_iva_cliente'] = cls._get_condicion_iva_cliente(Invoice, invoice)
  File "/trytond/modules/account_invoice_ar/invoice.py", line 737, in _get_condicion_iva_cliente
    return dict(invoice.party._fields['iva_condition'].selection)[invoice.party.iva_condition]
KeyError: None
```
Mirando en detalle, cuando entro a la entidad relacionada (cliente a facturar) desde la factura me aparece vacío el campo condición ante el iva. Pero si entro desde entidades a la misma entidad me aparece bien. El campo condición de iva se "vacía" cuando confirmás la factura, en los estados anteriores funciona bien y se puede imprimir sin errores.

**Comment by germanp** [comment]
Lo parchié provisoriamente para que no fallara, voy a buscar de nuevo el party y ahí si viene con la condición de iva bien.

https://github.com/Devecoop/account_invoice_ar/commit/738007c891d7546a1f6ee889635f61c49af0de0a

**Comment by lukio** [comment]
@germanp este error me parece medio raro porque en ningún momento se "vacia" la condición ante iva al confirmar una invoice. Adjunto imágen donde se visualiza correctamente la condición ante iva al ver la entidad desde una factura en estado confirmada.

![iva_condition_invoice_confirmed](https://cloud.githubusercontent.com/assets/776682/10695416/fc738f62-7979-11e5-8ead-e9ebcf88d060.png)
