### ISSUE TITLE
Error si no tiene períodos en el ejercicio fiscal

### ISSUE THREAD

**Issue by pablovannini** [tryton-ar/account_invoice_ar#6]
Si no tiene periodos en el ejercicio fiscal va a la afip, factura, pero no guarda factura de forma correcta

**Comment by lukio** [comment]
If this happens, the problem is that the operator must modify the sequence number, and create the new fiscal year with their periods.

**Comment by lukio** [comment]
Este mensaje se da cuando llama al metodo de get_move.
