### ISSUE TITLE
Error al Procesar Compra - Pide Tipo Comprobante

### ISSUE THREAD

**Issue by agumontagna** [tryton-ar/account_invoice_ar#68]
Hola! Volvió este error: 
Ya hay una solución hecha anteriormente en otro issue! #53 
Este error apareció al usar la versión 3.4.5

![selection_001](https://cloud.githubusercontent.com/assets/10468877/12644978/6e6a080e-c5a5-11e5-9e4b-bade03dda5e6.jpg)

**Comment by lukio** [comment]
@agumontagna hice la corrección en el branch release/3.4 
Si necesitas que genere un release para pypi avisame y lo hago.

Saludos!

**Comment by lukio** [comment]
hash: 236da960e8f74950e6fbc

**Comment by agumontagna** [comment]
@lukio no es necesario, ya toketie el código! 
Igual espero ya no usar más 3.4 en unos meses
Graciasss!!
