### ISSUE TITLE
python setup.py install error

### ISSUE THREAD

**Issue by s4msagaz** [tryton-ar/account_invoice_ar#79]
after try to install get

Processing dependencies for trytonar-account-invoice-ar==3.8.2
Searching for trytonspain_company_logo<3.9,>=3.8
Reading https://pypi.python.org/simple/trytonspain_company_logo/
No local packages or download links found for trytonspain_company_logo<3.9,>=3.8
error: Could not find suitable distribution for Requirement.parse('trytonspain_company_logo<3.9,>=3.8')

Looks like trytonspain_company_logo are just version 3.4

**Comment by lukio** [comment]
Try to install without execute setup.py
Just, download company_logo, and party_ar and copy them into modules folder.

https://bitbucket.org/trytonspain/trytond-company_logo
https://github.com/tryton-ar/party_ar

Install with pypi this packages:
requires.append('M2Crypto>=0.22.3')
requires.append('Pillow>=2.8.1')
requires.append('PySimpleSOAP==1.08.8')
requires.append('httplib2>=0.9.1')
requires.append('suds>=0.4')

And finally, download pyafipws and install into site-packages of your python installation.
https://github.com/reingart/pyafipws/tree/2.7.1872

Cheers!

**Comment by s4msagaz** [comment]
already tried that, but getting this error

Exception: Missing dependencies: ['party_ar']

will try with an clean install now.
