### ISSUE TITLE
Add field active to point of sales (pos)

### ISSUE THREAD

**Issue by lukio** [tryton-ar/account_invoice_ar#94]
I think it would be better to have an active field to this model, so we can set active or inactive to those point of sales without deleting them.

**Comment by marto87** [comment]
I added the field to point of sales model and I restricted "pos" field domain of invoice model to show only active ones. Should we check this new field in other modules?

**Comment by lukio** [comment]
@marto87 there is no need to filter by this field. Tryton does that automatically. You have to add a field named *active*, not *pos_active*.

Checkout this code:
https://bitbucket.org/tryton/party/src/3bdfa243dcbd57078f482d2f9d4cf26834e6d12c/address.py?at=default&fileviewer=file-view-default#address.py-46

And, then you have to add to the other fields the states attribute like:
https://bitbucket.org/tryton/party/src/3bdfa243dcbd57078f482d2f9d4cf26834e6d12c/address.py?at=default&fileviewer=file-view-default#address.py-20
https://bitbucket.org/tryton/party/src/3bdfa243dcbd57078f482d2f9d4cf26834e6d12c/address.py?at=default&fileviewer=file-view-default#address.py-34
